# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d90f04fb29d21e5232e050d8f42f19c04ad61af77b13199139a517748a87b2b644a7a4e6204c835818fcbb961c663522cfe08321e0c48c5e1a0dca5415df44ea

test:
  secret_key_base: d72619149363613a8d58220cefc71dd06569f96105045439cfe50e4c56ee1743fd737f1b80c3a70c01ecd7407e7850b1bea1ec4e301b59dd92f248c256f070ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
